### ISSUE TITLE
AUR pkgbuild

### ISSUE THREAD

**Issue by xDShot** [xveduk/toxygen#4]
please

**Comment by ingvar1995** [comment]
That's not so easy because of dependencies. Have you tried precompiled binary from [releases page](https://github.com/xveduk/toxygen/releases)? Anyway I can compile Toxygen for Arch using VM if you want to try Toxygen ASAP

**Comment by quininer** [comment]
https://aur.archlinux.org/packages/toxygen-git/

:)

**Comment by ingvar1995** [comment]
Thanks! I gonna test it today. Time to update master branch because it's broken and add client to pip3

**Comment by xDShot** [comment]
Thanks! :)
