### ISSUE TITLE
Bugs and TCS violations

### ISSUE THREAD

**Issue by JFreegman** [xveduk/toxygen#5]
Tested with the Linux binary, version 0.2.2

Bugs:
-Segfault on inbound friend request. No useful error message (cannot reproduce, possibly GUI related)
-Inbound file transfers with the same name as a file in the saving directory will fail and destroy the original file
-Fails to connect to DHT network with new or empty profiles
-Click spamming the friend request button locks the client up for a good 20 seconds

TCS violations:
1.0.3 DNS requests over proxy+forced tcp still leak your IP. You should be using wireshark to troubleshoot this.
5.0.1 Users are not given the option to encrypt their profile on creation

**Comment by ingvar1995** [comment]
Fixed all except the first one. if it occurs again please open new issue with more info about it
