### ISSUE TITLE
Minimize/Close to system tray

### ISSUE THREAD

**Issue by smaragdus** [xveduk/toxygen#6]
An option to minimize/close Toxygen to system tray will be welcome (Settings-Interface- "Miimize to Tray", "Close to Tray")- for example if "Minimize to Tray" is not selected but "Close to Tray" is selected the user would be able to minimize Toxygen to task-bar and close it to system tray.

I also think that a unified Settings panel with all Toxygen settings would be better.

**Comment by ingvar1995** [comment]
Press 'Esc' button and Toxygen will hide to tray.

**Comment by smaragdus** [comment]
"Escape" really minimizes Toxygen to tray but I expect double click on Toxygen tray icon to maximize it which does not work- I have to right-click on it and choose "Open Toxygen"- I think this should be achieved via single click or double click on tray icon.

**Comment by ingvar1995** [comment]
Double click is good idea. I will add it.

**Comment by smaragdus** [comment]
Thanks. I will do some more tests and if I find any issues I will report them here.

**Comment by ingvar1995** [comment]
Added in 546eb9f. Windows-only unfortunately
