### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by smaragdus** [xveduk/toxygen#7]
Now the Windows build of Toxygen saves data and settings in AppData (C:\Users\UserName\AppData\Roaming\tox). An option to run Toxygen in portable mode and save all its data and settings inside the program folder would be very handy- this will mean that the user would be able to copy the program folder containing all data and settings to an external drive and use Toxygen on other machines without leaving traces behind. This might be achieved via a "Portable Version" check-box in Settings which, when enabled, will copy all data to program folder and will use it on program's next start (something similar like in qTox).

**Comment by ingvar1995** [comment]
That's possible. You can export your profile to folder with .exe (or main.py) and on program's next start Toxygen will find it.

**Comment by smaragdus** [comment]
You are right but yet Toxygen creates "toxygen.json" in AppData (not using the same file in program folder).

**Comment by ingvar1995** [comment]
toxygen.json contains global Toxygen settings for current computer. So that's normal.

**Comment by smaragdus** [comment]
For me this is a bit contradictory to full portability, For example qTox only creates an empty folder (tox) in AppData while the global settings (qtox.ini) are also saved inside the program folder, So for me Toxygen is semi-portable but since the profile data from program folder is used this is OK.

**Comment by ingvar1995** [comment]
toxygen.json is unnecessary for portability. Toxygen saves path to default profile and info about profiles in use there. Nothing more.

**Comment by smaragdus** [comment]
This issue is closed but i have a question what about Toxygen asking users where to store data and settings at first run- AppData or Program Folder? This way the program will spare some efforts to cut/paste files. Another possibility- enabling portable mode from settings (like in qTox)- this will be of great help to less experienced users.

**Comment by ingvar1995** [comment]
At 1st run - during profile creation?

**Comment by smaragdus** [comment]
Yes, when the user is prompted to create a profile or load a profile- when neither AppData/tox no program folder contain any Tox profiles.

**Comment by ingvar1995** [comment]
I think I can add dialog for this purpose. And add 1 line fix that will help user export his profile to program folder easily.

**Comment by smaragdus** [comment]
It would be great, thanks. Because the nature of the protocol the more portable are the Tox clients the better. Easily triggered portable mode is a must for me- save data to program folder, archive/back-up/upload it and access it from anywhere.

One more tiny issue- it seems that Toxygen doesn't remember its windows position on desktop after restart (Windows 8 x64 here).

**Comment by ingvar1995** [comment]
Should work after fdfc745 on Windows. I'm woking on fix for Linux but it's not trivial
