### ISSUE TITLE
setup.py is broken

### ISSUE THREAD

**Issue by ProgVal** [xveduk/toxygen#8]
Running `python3 setup.py install --prefix=/tmp/foobar` leads to this error:

```
running install_egg_info
Copying Toxygen.egg-info to /tmp/foobar/lib/python3.4/site-packages/Toxygen-0.2.3.0-py3.4.egg-info
running install_scripts
Installing toxygen script to /tmp/foobar/bin
error: [Errno 2] No such file or directory: 'toxygen'
```

**Comment by Encrypt** [comment]
@ingvar1995 : Note that this bug prevents Toxygen from being build on pkg.tox.chat right now (https://build.tox.chat/job/toxygen_pkg_linux_deb_shared_xenial_x86_stable_release/).

Once fixed, it will hopefully build!

**Comment by ingvar1995** [comment]
1) /tmp/foobar/bin/ exists?
2) Is python module setuptools installed? (sudo apt-get install python3-setuptools)
Unfortunately my laptop died so I can't test it. Anyway I use the same setup.py on pip3 and it works.

**Comment by ProgVal** [comment]
On 21/07/2016 06:39, Ingvar wrote:
> 1) /tmp/foobar/bin/ exists?

Yes, it was created by setup.py

**Comment by ingvar1995** [comment]
Can you attach full installation log? Try python3 -m trace -t setup.py install

**Comment by ProgVal** [comment]
```
 progval@ion  /tmp/toxygen   master  python3 -m trace -t setup.py install --prefix=/tmp/foobar > setup_logs.txt
warning: no files found matching 'toxygen/libs/libtox.dll'
warning: no files found matching 'toxygen/libs/libsodium.a'
warning: no files found matching 'toxygen/libs/libtox64.dll'
warning: no files found matching 'toxygen/libs/libsodium64.a'
 progval@ion  /tmp/toxygen   master  gzip setup_logs.txt 


```

Gives this log: https://static.progval.net/public/toxygen_setup_logs.txt.gz
(Sorry I can't attach it, Github says it can't process that file.)

**Comment by ingvar1995** [comment]
Try to comment lines 21-25 in setup.py

**Comment by ProgVal** [comment]
It worked.

**Comment by ingvar1995** [comment]
I think try ... except block will solve this issue. But it needs testing.

**Comment by ingvar1995** [comment]
Fixed in develop
